- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Update hostname in /etc/hostname
  ansible.builtin.lineinfile:
    path: /etc/hostname
    regexp: '^.*$'
    line: "{{ hostname }}"

- name: Update hostname in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1\s.*$'
    line: "127.0.1.1 {{ hostname }}"
