- name: Remove snapd
  apt:
    name: snapd
    purge: true
    autoremove: true
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Install System Tools
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - software-properties-common
    - lsb-release
    - debian-archive-keyring
    - htop
    - nload
    - fail2ban
    - tmux
    - iotop
    - glances
    - wget
    - git
    - zip
    - curl
    state: latest
    update_cache: yes
    install_recommends: no
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable service fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
