---

- name: Ensure docker config file exists
  ansible.builtin.copy:
    content: "{}"
    dest: "{{ docker_config_path }}"
    owner: root
    group: root
    force: false
    mode: "0644"


- name: Get content of remote file
  slurp:
    src: "{{ docker_config_path }}"
  register: docker_config_encoded


- name: Read file directly into fact
  ansible.builtin.set_fact:
    jsondata: "{{ docker_config_encoded.content | b64decode }}"

- name: Configure docker
  ansible.builtin.copy:
    content: "{{ jsondata | combine(docker_config) | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart Docker

- name: Print docker config
  debug:
    msg: "{{ jsondata | combine(docker_config) | to_nice_json }}"
