- name: Start IPv6 NAT Docker container
  community.docker.docker_container:
    name: ipv6nat
    image: robbertkl/ipv6nat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_drop:
      - ALL
    capabilities:
      - NET_RAW
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    restart_policy: always
    state: started
    detach: yes

- name: configure docker mtu and ipv6
  ansible.builtin.copy:
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "fd00:1::/64",
        "userland-proxy": false,
        "default-address-pools": [
          { "base": "172.17.0.0/12", "size": 16 },
          { "base": "192.168.0.0/16", "size": 20 },
          {"base":"fd00:3::/48","size":64},
          {"base":"fd00:4::/48","size":64},
          {"base":"fd00:5::/48","size":64},
          {"base":"fd00:6::/48","size":64},
          {"base":"fd00:7::/48","size":64},
          {"base":"fd00:8::/48","size":64},
          {"base":"fd00:9::/48","size":64},
          {"base":"fd00:a::/48","size":64},
          {"base":"fd00:b::/48","size":64},
          {"base":"fd00:c::/48","size":64},
          {"base":"fd00:d::/48","size":64},
          {"base":"fd00:e::/48","size":64},
          {"base":"fd00:f::/48","size":64},
          {"base":"fd00:10::/48","size":64},
          {"base":"fd00:11::/48","size":64},
          {"base":"fd00:12::/48","size":64},
          {"base":"fd00:13::/48","size":64},
          {"base":"fd00:14::/48","size":64},
          {"base":"fd00:15::/48","size":64},
          {"base":"fd00:16::/48","size":64}
        ]
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker
