- name: Start IPv6 NAT Docker container
  community.docker.docker_container:
    name: ipv6nat
    image: robbertkl/ipv6nat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_drop:
      - ALL
    capabilities:
      - NET_RAW
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    restart_policy: always
    state: started
    detach: yes

- name: configure docker mtu and ipv6
  ansible.builtin.copy:
    content: |
      {
        "fixed-cidr-v6": "fd00:1::/64",
        "userland-proxy": false,
        "default-address-pools": [
          { "base": "172.17.0.0/12", "size": 16 },
          { "base": "192.168.0.0/16", "size": 20 },
          { "base": "fd00::/48", "size": 64 }
        ]
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker
